version: "3.7"

services:

  redis:
    container_name: redis
    image: redis:alpine3.11
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    
volumes:
  redis-data: